# Generated by Django 5.1.7 on 2026-01-06 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlog',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Null if this log is not related to a specific task/annotation', null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.AddField(
            model_name='userapikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstripeconnectaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_connect_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userstripeconnectaccount',
            index=models.Index(fields=['account_id'], name='account_use_account_123c59_idx'),
        ),
    ]
