# Generated by Django 5.1.7 on 2025-04-11 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_customuser_is_online_customuser_is_reviewer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_staff",
            new_name="is_admin",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_online",
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "reviewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reviewer_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
