# Generated by Django 5.1.7 on 2025-04-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_project_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="reviewers",
        ),
        migrations.AddField(
            model_name="customuser",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="account.project",
            ),
        ),
    ]
