# Generated by Django 5.1.7 on 2025-04-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_project_reviewers_customuser_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
