# Generated by Django 5.1.7 on 2025-04-15 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
