# Generated by Django 5.1.7 on 2025-05-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='key_type',
            field=models.CharField(choices=[('production', 'Production'), ('development', 'Development')], default='production', max_length=20),
        ),
    ]
