# Generated by Django 5.1.7 on 2025-05-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_userapikey_key_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='key_type',
            field=models.CharField(choices=[('production', 'Production'), ('test', 'Test')], default='production', max_length=20),
        ),
    ]
