# Generated by Django 5.1.7 on 2025-06-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_userapikey_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapikey',
            old_name='api_key',
            new_name='plain_api_key',
        ),
    ]
