# Generated by Django 5.1.7 on 2025-06-10 16:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_rename_api_key_userapikey_plain_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
