# Generated by Django 5.1.7 on 2025-06-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_otpverification_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='cloudinary_data',
            field=models.JSONField(blank=True, help_text='The full result from gotten when uploading the image to cloudinary', null=True),
        ),
    ]
