# Generated by Django 5.1.7 on 2025-07-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_annotationlog'),
        ('task', '0014_delete_annotationlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnnotationLog',
            new_name='ProjectLog',
        ),
    ]
