# Generated by Django 5.1.7 on 2025-07-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
