# Generated by Django 5.1.7 on 2025-08-21 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple choice')], default='text', help_text='The type of input the labeller is to provide', max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='labeller_instructions',
            field=models.TextField(default='Default'),
        ),
        migrations.AddField(
            model_name='project',
            name='labeller_per_item_count',
            field=models.IntegerField(default=100),
        ),
    ]
