# Generated by Django 5.1.7 on 2025-08-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_project_deadline_project_input_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='input_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='labeller_instructions',
        ),
        migrations.RemoveField(
            model_name='project',
            name='labeller_per_item_count',
        ),
    ]
