# Generated by Django 5.1.7 on 2025-09-16 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_remove_project_deadline_remove_project_input_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelerEarnings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labeler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labeler_earnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
