# Generated by Django 5.1.7 on 2025-09-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_labelerearnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelerearnings',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The balance of the labeler in USD', max_digits=10),
        ),
    ]
