# Generated by Django 5.1.7 on 2025-09-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_labelerearnings_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelerDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='domains',
            field=models.ManyToManyField(blank=True, help_text='The domains of expertise that the labeler is allowed to label', null=True, related_name='labelers', to='account.labelerdomain'),
        ),
    ]
