# Generated by Django 5.1.7 on 2025-09-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_labelerdomain_customuser_domains'),
        ('reviewer', '0001_initial'),
        ('task', '0040_alter_taskcluster_labeler_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabelerDomain',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='domains',
            field=models.ManyToManyField(blank=True, help_text='The domains of expertise that the labeler is allowed to label', related_name='labelers', to='reviewer.labelerdomain'),
        ),
    ]
