# Generated by Django 5.1.7 on 2025-09-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_userbankaccount_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='platform',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe')], default='paystack', help_text='The platform of the bank account, e.g. paystack, flutterwave, etc.', max_length=255),
        ),
    ]
