# Generated by Django 5.1.7 on 2025-09-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_monthlyreviewerearnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreviewerearnings',
            name='earnings',
        ),
    ]
