# Generated by Django 5.1.7 on 2025-10-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_remove_monthlyreviewerearnings_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreviewerearnings',
            name='paid',
            field=models.BooleanField(default=False, help_text='Whether the reviewer has been paid for this month'),
        ),
    ]
