# Generated by Django 5.1.7 on 2025-10-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_monthlyreviewerearnings_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreviewerearnings',
            name='paid',
        ),
        migrations.AddField(
            model_name='monthlyreviewerearnings',
            name='release_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('released', 'Released'), ('failed', 'Failed')], default='pending', help_text='Indicates if the earnings for this month has been released to the reviewer', max_length=50),
        ),
    ]
