# Generated by Django 5.1.7 on 2025-10-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_remove_monthlyreviewerearnings_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreviewerearnings',
            name='total_earnings_usd',
            field=models.DecimalField(decimal_places=4, default=0, help_text='The total earnings of the reviewer in USD for this month', max_digits=10),
        ),
    ]
