# Generated by Django 5.1.7 on 2025-10-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_userstripeconnectaccount_delete_labelerearnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstripeconnectaccount',
            name='payouts_enabled',
            field=models.BooleanField(default=False, help_text='Indicates if the stripe connect account has payouts enabled'),
        ),
    ]
