# Generated by Django 5.1.7 on 2025-10-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_userstripeconnectaccount_payouts_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstripeconnectaccount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('disabled', 'Disabled')], default='pending', help_text='The status of the stripe connect account', max_length=255),
        ),
    ]
