# Generated by Django 5.1.7 on 2025-10-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_alter_userstripeconnectaccount_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userstripeconnectaccount',
            index=models.Index(fields=['account_id'], name='account_use_account_123c59_idx'),
        ),
    ]
