# Generated by Django 5.1.7 on 2025-10-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_userstripeconnectaccount_account_use_account_123c59_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the email of the user has been verified'),
        ),
    ]
