"""
Django settings for label_x project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
import logging
from logging import config as logging_config
import os
from pathlib import Path
from celery.schedules import crontab

from decouple import config, Csv
import pytz
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
from sentry_sdk.integrations.redis import RedisIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import dj_database_url
import cloudinary
import cloudinary.uploader
import cloudinary.api
import cloudinary_storage


# python-decouple automatically handles .env file loading
# Environment variables take precedence over .env file values
# This ensures docker-compose environment variables override .env file values

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY_VALUE", default="default")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG_VALUE", default="true", cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS_VALUE", default="127.0.0.1", cast=Csv())
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS_VALUE", default="http://127.0.0.1", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "daphne",
    "account",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_api_key",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "task",
    "corsheaders",
    "api_auth",
    "common",
    "subscription",
    'cloudinary',
    'django_celery_beat',
    'cloudinary_storage',
    "datasets",
    "payment",
    "reviewer",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "label_x.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "label_x.wsgi.application"
ASGI_APPLICATION = "label_x.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
if config("IS_PRODUCTION", default=False, cast=bool):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": config("PROD_DB_NAME", default=""),
            "USER": config("PROD_DB_USER", default=""),
            "PASSWORD": config("PROD_DB_PASSWORD", default=""),
            "HOST": config("PROD_DB_HOST", default=""),
            "PORT": config("PROD_DB_PORT", default=""),
            # Connection pooling for API performance (stateless, shorter duration)
            "CONN_MAX_AGE": 300,  # 5 minutes - shorter for stateless API
            "CONN_HEALTH_CHECKS": True,  # Verify connection health before reuse
            "OPTIONS": {
                "connect_timeout": 10,
                # Connection pool settings for pgbouncer compatibility
                "options": "-c statement_timeout=30000",  # 30 second query timeout
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {
                "timeout": 20,  # 20 second timeout for database operations
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_FILES_DIR = [
    BASE_DIR / "main" / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# MEDIA_URL = "media/"
# MEDIA_ROOT = BASE_DIR / "media"



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# custom user model for authentication
AUTH_USER_MODEL = "account.User"

# setting for logging of errors


LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO", #Level is the minimum severity that will be handled in order of DEBUG < INFO < WARNING < ERROR < CRITICAL
            "class": "logging.FileHandler",
            "filename": "logs/api_activity.log",
            "formatter": "verbose",
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": "logs/errors.log",
            "formatter": "verbose",
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file", "error_file"],
        "level": "INFO",
        "propagate": True,
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "account": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "account.apis": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "task": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "task.apis": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "task.tasks": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "payment": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "payment.apis": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "payment.tasks": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "subscription": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "subscription.apis": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "reviewer": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "reviewer.apis": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "api_auth": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "api_auth.apis": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.server": { 
            "handlers": ["console", "file", "error_file"],
            "propagate": False,
        },
        "default": {
            "handlers": ["console", "file", "error_file"],
            "propagate": True,
        }
    },
}

# settings for django restAPI
REST_FRAMEWORK = {
    "REST_FRAMEWORK_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "15/min",
        "user": "30/min",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        # "rest_framework.permissions.AllowAny"
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}

# JWT Timeout settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=2),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# celery settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
# python-decouple automatically prioritizes environment variables over .env file
# This ensures docker-compose environment variables override .env file values
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://localhost:6379/0")
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CORS_ALLOW_ALL_ORIGINS = True

# Sentry settings
sentry_sdk.init(
    dsn=config("SENTRY_DSN", default=""),
    integrations=[
        DjangoIntegration(),
        LoggingIntegration(level=logging.INFO, event_level=logging.ERROR),
        RedisIntegration(),
    ],
    send_default_pii=True,
)


# CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}
REDIS_URL = config("CELERY_RESULT_BACKEND", default="redis://localhost:6379/0")
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

API_KEY_CUSTOM_HEADER = "HTTP_X_API_KEY"
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")
STRIPE_CONNECT_WEBHOOK_SECRET = config("STRIPE_CONNECT_WEBHOOK_SECRET", default="")

SPECTACULAR_SETTINGS = {
    "TITLE": "Label x api",
    "VERSION": "1.0.0",
    "DESCRIPTION": "Official documentation for Enuda labs Label_x AI classifier",
    "SCHEMA_PATH_PREFIX": r"/api/v[0-9]",
}


CLOUDINARY_CLOUD_NAME = config("CLOUDINARY_CLOUD_NAME", default="")
CLOUDINARY_API_KEY = config("CLOUDINARY_API_KEY", default="")
CLOUDINARY_API_SECRET = config("CLOUDINARY_API_SECRET", default="")


CO_API_KEY = config("CO_API_KEY", default="")

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
    'API_KEY': CLOUDINARY_API_KEY,
    'API_SECRET': CLOUDINARY_API_SECRET,
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

if not DEBUG:    
    CSRF_TRUSTED_ORIGINS = [
        "https://label-x-dock.onrender.com"]
    
# Use REDIS_CACHE_BACKEND if set, otherwise fallback to REDIS_URL or default
REDIS_CACHE_BACKEND = config("REDIS_CACHE_BACKEND", default=config("REDIS_URL", default="redis://localhost:6379/1"))
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CACHE_BACKEND,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

PAYSTACK_SECRET_KEY = config("PAYSTACK_SECRET_KEY", default="")
PAYSTACK_PUBLIC_KEY = config("PAYSTACK_PUBLIC_KEY", default="")
EXCHANGE_RATE_API_KEY = config("EXCHANGE_RATE_API_KEY", default="")



CELERY_TIMEZONE = 'UTC'


#runs at 7 am, 12pm and 4pm starting from the 28th of the month to the 10th of the next month
#the reason i start at 28th is because of February which has only 28 days
#the reason i end at 10th is for payment processing to continue till the next month, giving the system enough time to retry failed payments
CELERY_BEAT_SCHEDULE = {
   "process_pending_payments": { 
       "task": "payment.tasks.process_pending_payments",
       "schedule": crontab(
            minute=0,
            hour="7,12,16",
            day_of_month="28-31,1-10"
        ),
   },
#    "process_pending_payments": { 
#        "task": "payment.tasks.process_pending_payments",
#        "schedule": crontab(minute="*"),
#    },
    # "test_task_every_2_minutes": {
    #     "task": "payment.tasks.test_task",
    #     "schedule": crontab(minute="*/2"),
    # },
}

BREVO_API_KEY = config("BREVO_API_KEY", default="")
BREVO_FROM_EMAIL = config("BREVO_FROM_EMAIL", default="")

AUTHENTICATION_BACKENDS = [
    'account.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]