# Generated by Django 5.1.7 on 2026-01-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text="List of features for this plan (e.g., ['Up to 10,000 data points', '48-hour turnaround time'])"),
        ),
    ]
