# Generated by Django 5.1.7 on 2025-05-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionplan_stripe_plan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='stripe_plan_id',
            new_name='stripe_monthly_plan_id',
        ),
    ]
