# Generated by Django 5.1.7 on 2025-05-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_userpaymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymenthistory',
            name='payment_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
