# Generated by Django 5.1.7 on 2025-07-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_userpaymenthistory_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='included_data_points',
            field=models.IntegerField(default=0, help_text='Number of data points user gets when they subscribe to this plan'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='remaining_data_points',
            field=models.IntegerField(default=0),
        ),
    ]
