# Generated by Django 5.1.7 on 2025-07-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_userdatapoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='remaining_data_points',
        ),
        migrations.AddField(
            model_name='userdatapoints',
            name='used_data_points',
            field=models.IntegerField(default=0),
        ),
    ]
