# Generated by Django 5.1.7 on 2026-01-06 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ngn_amount', models.DecimalField(blank=True, decimal_places=2, help_text='The amount in NGN at the time of the transaction', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('monthly_payment', 'Monthly Payment')], default='withdrawal', max_length=50)),
                ('description', models.TextField(blank=True, help_text='The description of the transaction', null=True)),
                ('failed_reason', models.TextField(blank=True, help_text='The reason the transaction failed if any', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('bank_code', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('is_user_balance_deducted', models.BooleanField(default=False, help_text="Whether the user's balance has been deducted for this withdrawal request")),
                ('initiated_by', models.CharField(choices=[('user', 'User'), ('system', 'System')], default='user', help_text='Whether the withdrawal request was initiated by the user or the system', max_length=50)),
                ('monthly_earning', models.ForeignKey(blank=True, help_text='If this withdrawal request was made for a particular monthly earning, this field will be populated', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.monthlyreviewerearnings')),
                ('transaction', models.ForeignKey(blank=True, help_text='The transaction that this withdrawal request is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['reference'], name='payment_wit_referen_57f605_idx')],
            },
        ),
    ]
