# Generated by Django 5.1.7 on 2025-09-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='amount',
            new_name='usd_amount',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='ngn_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The amount in NGN', max_digits=10, null=True),
        ),
    ]
