# Generated by Django 5.1.7 on 2025-09-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_amount_withdrawalrequest_usd_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='is_user_balance_deducted',
            field=models.BooleanField(default=False, help_text="Whether the user's balance has been deducted for this withdrawal request"),
        ),
    ]
