# Generated by Django 5.1.7 on 2025-09-22 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_withdrawalrequest_is_user_balance_deducted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='ngn_amount',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='usd_amount',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ngn_amount', models.DecimalField(blank=True, decimal_places=2, help_text='The amount in NGN', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('withdrawal', 'Withdrawal'), ('deposit', 'Deposit')], default='withdrawal', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='The transaction that this withdrawal request is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.transaction'),
        ),
    ]
