# Generated by Django 5.1.7 on 2025-09-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_withdrawalrequest_ngn_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='user',
        ),
    ]
