# Generated by Django 5.1.7 on 2025-09-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_withdrawalrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='The description of the transaction', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ngn_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The amount in NGN at the time of the transaction', max_digits=10, null=True),
        ),
    ]
