# Generated by Django 5.1.7 on 2025-09-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_transaction_description_alter_transaction_ngn_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='initiated_by',
            field=models.CharField(choices=[('user', 'User'), ('system', 'System')], default='user', help_text='Whether the withdrawal request was initiated by the user or the system', max_length=50),
        ),
    ]
