# Generated by Django 5.1.7 on 2025-09-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_transaction_transaction_type_monthlypayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlypayment',
            old_name='amount',
            new_name='usd_amount',
        ),
    ]
