# Generated by Django 5.1.7 on 2025-09-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_rename_amount_monthlypayment_usd_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='failed_reason',
            field=models.TextField(blank=True, help_text='The reason the transaction failed if any', null=True),
        ),
    ]
