# Generated by Django 5.1.7 on 2025-09-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_withdrawalrequest_initiated_by'),
        ('payment', '0009_transaction_failed_reason'),
    ]

    operations = [
    ]
