# Generated by Django 5.1.7 on 2025-10-01 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_monthlyreviewerearnings_paid'),
        ('payment', '0010_merge_20250927_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlypayment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='usd_amount',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='year',
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='earning',
            field=models.ForeignKey(blank=True, help_text='The earning that this payment is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.monthlyreviewerearnings'),
        ),
    ]
