# Generated by Django 5.1.7 on 2025-10-01 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_remove_monthlyreviewerearnings_paid_and_more'),
        ('payment', '0011_remove_monthlypayment_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='monthly_earning',
            field=models.ForeignKey(blank=True, help_text='If this withdrawal request was made for a particular monthly earning, this field will be populated', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.monthlyreviewerearnings'),
        ),
    ]
