# Generated by Django 5.1.7 on 2025-10-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_monthlyreviewerearnings_total_earnings_usd'),
        ('payment', '0012_withdrawalrequest_monthly_earning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlypayment',
            name='earning',
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['reference'], name='payment_wit_referen_57f605_idx'),
        ),
        migrations.DeleteModel(
            name='MonthlyPayment',
        ),
    ]
