# Generated by Django 5.1.7 on 2026-01-06 10:59

import django.db.models.deletion
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('reviewer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('description', models.TextField(default='Default')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple choice'), ('voice', 'Voice'), ('image', 'Image'), ('video', 'Video')], default='text', help_text='The type of input the labeller is to provide for the tasks in this cluster', max_length=25)),
                ('labeller_instructions', models.TextField(default='Default')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('labeller_per_item_count', models.IntegerField(default=15)),
                ('task_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('CSV', 'Csv'), ('MULTIMODAL', 'Multimodal')], default='TEXT', max_length=25)),
                ('annotation_method', models.CharField(choices=[('manual', 'Manual'), ('ai_automated', 'Ai automated')], default='ai_automated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In review'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('completion_percentage', models.FloatField(default=0, help_text='The percentage of the tasks in this cluster that has been labelled by the reviewers')),
                ('assigned_reviewers', models.ManyToManyField(blank=True, help_text='Users assigned to review the tasks in this cluster', related_name='assigned_clusters', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this cluster', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_clusters', to=settings.AUTH_USER_MODEL)),
                ('labeler_domain', models.ForeignKey(blank=True, help_text='The domain of expertise that the labeler is allowed to label', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='reviewer.labelerdomain')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='account.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(default=task.models.generate_serial_no, editable=False, help_text='Auto-generated 6-digit alphanumeric identifier', max_length=6, unique=True)),
                ('task_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('CSV', 'Csv'), ('MULTIMODAL', 'Multimodal')], default='TEXT', help_text='Type of content to be processed', max_length=10)),
                ('data', models.TextField()),
                ('predicted_label', models.JSONField(blank=True, help_text='AI-generated predictions', null=True)),
                ('ai_output', models.JSONField(blank=True, help_text='The full json output of the ai model', null=True)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('final_label', models.JSONField(blank=True, help_text='Human-reviewed final label', null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('REVIEW_NEEDED', 'Review Needed'), ('ASSIGNED_REVIEWER', 'Assigned Reviewer'), ('COMPLETED', 'Completed'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=17)),
                ('review_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('PENDING_APPROVAL', 'Pending Approval'), ('COMPLETED', 'Completed')], default=None, max_length=17, null=True)),
                ('human_reviewed', models.BooleanField(default=False, help_text='Indicates if a human has reviewed this task')),
                ('priority', models.CharField(choices=[('URGENT', 'Urgent'), ('NORMAL', 'Normal'), ('LOW', 'Low')], default='NORMAL', help_text='Task processing priority level', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_data_points', models.IntegerField(default=0, help_text='The amount of data points that was used during the submission of this task')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_url', models.URLField(blank=True, help_text='The cdn link to the file', null=True)),
                ('file_size_bytes', models.FloatField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to review this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Group who created the task', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='account.project')),
                ('user', models.ForeignKey(blank=True, help_text='User who created the task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.taskcluster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=100)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='task.taskcluster')),
            ],
        ),
        migrations.CreateModel(
            name='ManualReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed')], default='started', max_length=50)),
                ('labeller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.taskcluster')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='The text label if the submission type for the task is text', max_length=255, null=True)),
                ('label_file_url', models.URLField(blank=True, help_text='The url of the file label if the submission type for the task is a e.g a voice recording, video, image, etc', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(null=True)),
                ('subtitles_url', models.URLField(blank=True, help_text='The url of the subtitles of the labeller for the task if any', null=True)),
                ('labeller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
        migrations.CreateModel(
            name='UserReviewChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_output', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('human_confidence_score', models.FloatField()),
                ('human_justification', models.TextField()),
                ('human_classification', models.CharField(choices=[('Safe', 'Safe'), ('Mildly Offensive', 'Mildly Offensive'), ('Highly Offensive', 'Highly Offensive')], max_length=25)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['serial_no'], name='task_task_serial__1230ed_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['processing_status'], name='task_task_process_7175c9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type'], name='task_task_task_ty_56e246_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['human_reviewed'], name='task_task_human_r_c5c651_idx'),
        ),
    ]
