# Generated by Django 5.1.4 on 2025-03-10 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="confidence_threshold",
            field=models.FloatField(default=0.9),
        ),
        migrations.AddField(
            model_name="task",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="content/"),
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("URGENT", "Urgent"), ("NORMAL", "Normal"), ("LOW", "Low")],
                default="NORMAL",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("AI_REVIEWED", "AI Reviewed"),
                    ("HUMAN_REVIEW_NEEDED", "Human Review Needed"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[("TEXT", "Text"), ("IMAGE", "Image"), ("VIDEO", "Video")],
                max_length=10,
            ),
        ),
    ]
