# Generated by Django 5.1.4 on 2025-03-21 10:41

import django.db.models.deletion
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_task_confidence_threshold_task_file_task_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="task",
            name="confidence_threshold",
        ),
        migrations.RemoveField(
            model_name="task",
            name="content",
        ),
        migrations.RemoveField(
            model_name="task",
            name="file",
        ),
        migrations.RemoveField(
            model_name="task",
            name="priority",
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned to review this task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="data",
            field=models.JSONField(
                default="hello world",
                help_text="Task data (text content, file URLs, etc.)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="final_label",
            field=models.JSONField(
                blank=True, help_text="Human-reviewed final label", null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="human_reviewed",
            field=models.BooleanField(
                default=False, help_text="Indicates if a human has reviewed this task"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="predicted_label",
            field=models.JSONField(
                blank=True, help_text="AI-generated predictions", null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="serial_no",
            field=models.CharField(
                default=task.models.generate_serial_no,
                editable=False,
                help_text="Auto-generated 6-digit alphanumeric identifier",
                max_length=6,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("REVIEW_NEEDED", "Review Needed"),
                    ("COMPLETED", "Completed"),
                    ("ESCALATED", "Escalated"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("IMAGE", "Image"),
                    ("VIDEO", "Video"),
                    ("AUDIO", "Audio"),
                    ("MULTIMODAL", "Multimodal"),
                ],
                help_text="Type of content to be processed",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                help_text="User who created the task",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["serial_no"], name="task_task_serial__1230ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="task_task_status_5e4c6f_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["task_type"], name="task_task_task_ty_56e246_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["human_reviewed"], name="task_task_human_r_c5c651_idx"
            ),
        ),
    ]
