# Generated by Django 5.1.4 on 2025-03-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_alter_task_options_remove_task_confidence_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("URGENT", "Urgent"), ("NORMAL", "Normal"), ("LOW", "Low")],
                default="NORMAL",
                help_text="Task processing priority level",
                max_length=10,
            ),
        ),
    ]
