# Generated by Django 5.1.7 on 2025-04-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_output',
            field=models.JSONField(blank=True, help_text='The full json output of the ai model', null=True),
        ),
    ]
