# Generated by Django 5.1.7 on 2025-04-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_task_ai_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("REVIEW_NEEDED", "Review Needed"),
                    ("PENDING_REVIEWER", "Pending Reviewer"),
                    ("COMPLETED", "Completed"),
                    ("ESCALATED", "Escalated"),
                ],
                default="PENDING",
                max_length=17,
            ),
        ),
    ]
