# Generated by Django 5.1.7 on 2025-04-11 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_rename_is_staff_customuser_is_admin_and_more"),
        ("task", "0006_alter_task_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="task",
            name="task_task_status_5e4c6f_idx",
        ),
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.AddField(
            model_name="task",
            name="group",
            field=models.ForeignKey(
                default=1,
                help_text="Group who created the task",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to="account.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("REVIEW_NEEDED", "Review Needed"),
                    ("ASSIGNED_REVIEWER", "Assigned Reviewer"),
                    ("COMPLETED", "Completed"),
                    ("ESCALATED", "Escalated"),
                ],
                default="PENDING",
                max_length=17,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("PENDING_REVIEW", "Pending Review"),
                    ("PENDING_APPROVAL", "Pending Arpoval"),
                    ("COMPLETED", "Completed"),
                ],
                default=None,
                max_length=17,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["processing_status"], name="task_task_process_7175c9_idx"
            ),
        ),
    ]
