# Generated by Django 5.1.7 on 2025-04-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0008_task_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("PENDING_REVIEW", "Pending Review"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("COMPLETED", "Completed"),
                ],
                default=None,
                max_length=17,
                null=True,
            ),
        ),
    ]
