# Generated by Django 5.1.7 on 2025-04-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_userreviewchathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviewchathistory',
            name='ai_output',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
