# Generated by Django 5.1.7 on 2025-07-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_annotationlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnotationLog',
        ),
    ]
