# Generated by Django 5.1.7 on 2025-07-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_delete_annotationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='used_data_points',
            field=models.IntegerField(default=0),
        ),
    ]
