# Generated by Django 5.1.7 on 2025-07-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_task_used_data_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
