# Generated by Django 5.1.7 on 2025-08-21 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_task_ai_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='used_data_points',
            field=models.IntegerField(default=0, help_text='The amount of data points that was used during the submission of this task'),
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=10)),
                ('url', models.URLField(help_text='The cdn link to the file')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
