# Generated by Django 5.1.7 on 2025-08-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_alter_task_used_data_points_taskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='file_url',
            field=models.URLField(blank=True, help_text='The cdn link to the file', null=True),
        ),
        migrations.DeleteModel(
            name='TaskFile',
        ),
    ]
