# Generated by Django 5.1.7 on 2025-08-21 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_remove_project_deadline_remove_project_input_type_and_more'),
        ('task', '0018_task_file_name_task_file_type_task_file_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple choice')], default='text', help_text='The type of input the labeller is to provide for the tasks in this cluster', max_length=25)),
                ('labeller_instructions', models.TextField(default='Default')),
                ('deadline', models.DateField()),
                ('labeller_per_item_count', models.IntegerField(default=100)),
                ('task_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('MULTIMODAL', 'Multimodal')], default='TEXT', max_length=25)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to review the tasks in this cluster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clusters', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.project')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.taskcluster'),
        ),
    ]
