# Generated by Django 5.1.7 on 2025-08-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_taskcluster_task_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcluster',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
