# Generated by Django 5.1.7 on 2025-08-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_alter_taskcluster_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcluster',
            name='annotation_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai_automated', 'Ai automated')], default='ai_automated', max_length=20),
        ),
    ]
