# Generated by Django 5.1.7 on 2025-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_taskcluster_annotation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('CSV', 'Csv'), ('MULTIMODAL', 'Multimodal')], default='TEXT', help_text='Type of content to be processed', max_length=10),
        ),
        migrations.AlterField(
            model_name='taskcluster',
            name='task_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('CSV', 'Csv'), ('MULTIMODAL', 'Multimodal')], default='TEXT', max_length=25),
        ),
    ]
