# Generated by Django 5.1.7 on 2025-08-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_alter_task_task_type_alter_taskcluster_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_size_bytes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
