# Generated by Django 5.1.7 on 2025-08-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_task_file_size_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='data',
            field=models.JSONField(blank=True, help_text='Task data (text content, file URLs, etc.)', null=True),
        ),
    ]
