# Generated by Django 5.1.7 on 2025-08-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_tasklabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='data',
            field=models.TextField(),
        ),
    ]
