# Generated by Django 5.1.7 on 2025-08-21 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_alter_task_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskClusterMultiChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=100)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.taskcluster')),
            ],
        ),
    ]
