# Generated by Django 5.1.7 on 2025-08-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_taskclustermultichoiceoption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskClusterMultiChoiceOption',
            new_name='MultiChoiceOption',
        ),
    ]
