# Generated by Django 5.1.7 on 2025-08-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0025_alter_task_data"),
    ]

    operations = []
