# Generated by Django 5.1.7 on 2025-08-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_rename_taskclustermultichoiceoption_multichoiceoption'),
        ('task', '0026_task_file_size_bytes'),
    ]

    operations = [
    ]
