# Generated by Django 5.1.7 on 2025-08-22 10:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0027_merge_20250822_0854'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcluster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcluster',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this cluster', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_clusters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcluster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='data',
            field=models.TextField(default='defualt'),
            preserve_default=False,
        ),
    ]
