# Generated by Django 5.1.7 on 2025-08-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0028_taskcluster_created_at_taskcluster_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcluster',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In review'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
