# Generated by Django 5.1.7 on 2025-08-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0030_manualreviewsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualreviewsession',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed')], default='started', max_length=50),
        ),
    ]
