# Generated by Django 5.1.7 on 2025-08-25 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0031_alter_manualreviewsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoiceoption',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='task.taskcluster'),
        ),
    ]
