# Generated by Django 5.1.7 on 2025-08-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0032_alter_multichoiceoption_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklabel',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
