# Generated by Django 5.1.7 on 2025-08-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0033_tasklabel_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcluster',
            options={'ordering': ['-created_at']},
        ),
    ]
