# Generated by Django 5.1.7 on 2025-09-09 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_remove_project_deadline_remove_project_input_type_and_more'),
        ('task', '0034_alter_taskcluster_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcluster',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='account.project'),
        ),
    ]
