# Generated by Django 5.1.7 on 2025-09-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0035_alter_taskcluster_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklabel',
            name='label_file_url',
            field=models.URLField(blank=True, help_text='The url of the file label if the submission type for the task is a e.g a voice recording, video, image, etc', null=True),
        ),
        migrations.AlterField(
            model_name='tasklabel',
            name='label',
            field=models.CharField(blank=True, help_text='The text label if the submission type for the task is text', max_length=255, null=True),
        ),
    ]
