# Generated by Django 5.1.7 on 2025-09-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0036_tasklabel_label_file_url_alter_tasklabel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcluster',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple choice'), ('voice', 'Voice'), ('image', 'Image'), ('video', 'Video')], default='text', help_text='The type of input the labeller is to provide for the tasks in this cluster', max_length=25),
        ),
    ]
