# Generated by Django 5.1.7 on 2025-09-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0037_alter_taskcluster_input_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcluster',
            name='completion_percentage',
            field=models.FloatField(default=0, help_text='The percentage of the tasks in this cluster that has been labelled by the reviewers'),
        ),
        migrations.AlterField(
            model_name='taskcluster',
            name='labeller_per_item_count',
            field=models.IntegerField(default=15),
        ),
    ]
