# Generated by Django 5.1.7 on 2025-09-20 19:55

import django.db.models.deletion
import task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_labelerdomain_customuser_domains'),
        ('task', '0038_taskcluster_completion_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcluster',
            name='labeler_domain',
            field=models.ForeignKey(default=task.models.get_default_labeler_domain, help_text='The domain of expertise that the labeler is allowed to label', on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='account.labelerdomain'),
        ),
    ]
