# Generated by Django 5.1.7 on 2025-09-20 22:29

import django.db.models.deletion
import task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
        ('task', '0039_taskcluster_labeler_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcluster',
            name='labeler_domain',
            field=models.ForeignKey(default=task.models.get_default_labeler_domain, help_text='The domain of expertise that the labeler is allowed to label', on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='reviewer.labelerdomain'),
        ),
    ]
