# Generated by Django 5.1.7 on 2025-09-22 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
        ('task', '0040_alter_taskcluster_labeler_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcluster',
            name='labeler_domain',
            field=models.ForeignKey(blank=True, help_text='The domain of expertise that the labeler is allowed to label', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='reviewer.labelerdomain'),
        ),
    ]
