# Generated by Django 5.1.7 on 2025-10-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0041_alter_taskcluster_labeler_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcluster',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskcluster',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
