# Generated by Django 5.1.7 on 2025-10-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0042_taskcluster_description_taskcluster_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcluster',
            name='description',
            field=models.TextField(default='Default'),
        ),
        migrations.AlterField(
            model_name='taskcluster',
            name='name',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
