# Generated by Django 5.1.7 on 2025-10-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0043_alter_taskcluster_description_alter_taskcluster_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
