# Generated by Django 5.1.7 on 2025-10-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0044_alter_task_file_name_alter_task_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklabel',
            name='labeller_subtitles_url',
            field=models.URLField(blank=True, help_text='The url of the subtitles of the labeller for the task if any', null=True),
        ),
    ]
