# Generated by Django 5.1.7 on 2025-10-12 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0045_tasklabel_labeller_subtitles_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklabel',
            old_name='labeller_subtitles_url',
            new_name='subtitles_url',
        ),
    ]
